import React from 'react';
import {
  ArrowPathIcon,
  CheckCircleIcon,
  DocumentArrowDownIcon,
} from '@heroicons/react/24/outline';

export interface DatasetConfig {
  id: string;
  name: string;
  description: string;
  records: string;
  size: string;
  format: string;
}

export interface UseCaseDatasets {
  [key: string]: DatasetConfig[];
}

export const preloadedDatasets: UseCaseDatasets = {
  'oilfield-lease': [
    {
      id: 'historical-lease',
      name: 'Historical Lease Portfolio',
      description: '5 years of lease data including terms, renewals, and financial performance',
      records: '1,247 leases',
      size: '2.3 GB',
      format: 'CSV format',
    },
    {
      id: 'contract-docs',
      name: 'Contract Documents',
      description: 'Scanned lease agreements, amendments, and related legal documents',
      records: '3,892 documents',
      size: '18.7 GB',
      format: 'PDF format',
    },
    {
      id: 'gis-data',
      name: 'GIS & Geological Data',
      description: 'Spatial data, well locations, production zones, and geological surveys',
      records: '847 layers',
      size: '5.6 GB',
      format: 'GeoJSON/SHP',
    },
    {
      id: 'financial-models',
      name: 'Financial Models',
      description: 'NPV calculations, production forecasts, and economic evaluations',
      records: '423 models',
      size: '892 MB',
      format: 'Excel/JSON',
    },
  ],
  'grid-anomaly': [
    {
      id: 'scada-telemetry',
      name: 'SCADA Telemetry Data',
      description: 'Real-time sensor readings from substations and transmission lines',
      records: '2.5M readings',
      size: '8.7 GB',
      format: 'Time-series DB',
    },
    {
      id: 'weather-patterns',
      name: 'Weather Pattern Data',
      description: 'Historical weather conditions correlated with grid events',
      records: '5 years history',
      size: '3.2 GB',
      format: 'NetCDF/JSON',
    },
    {
      id: 'outage-history',
      name: 'Outage History',
      description: 'Past outage events with root cause analysis',
      records: '12,847 events',
      size: '1.8 GB',
      format: 'CSV/JSON',
    },
    {
      id: 'asset-topology',
      name: 'Asset Topology',
      description: 'Grid infrastructure layout and connectivity model',
      records: '45K assets',
      size: '2.4 GB',
      format: 'GraphML/JSON',
    },
  ],
  'patient-risk': [
    {
      id: 'ehr-records',
      name: 'EHR Records',
      description: 'De-identified patient medical histories and diagnoses',
      records: '250K patients',
      size: '12.3 GB',
      format: 'FHIR/JSON',
    },
    {
      id: 'claims-data',
      name: 'Claims Data',
      description: 'Insurance claims history with cost and utilization patterns',
      records: '1.8M claims',
      size: '6.5 GB',
      format: 'CSV/Parquet',
    },
    {
      id: 'social-determinants',
      name: 'Social Determinants',
      description: 'Socioeconomic factors affecting health outcomes',
      records: 'Geographic data',
      size: '890 MB',
      format: 'GeoJSON/CSV',
    },
    {
      id: 'lab-results',
      name: 'Lab Results',
      description: 'Clinical laboratory test results and biomarkers',
      records: '5.2M tests',
      size: '4.1 GB',
      format: 'HL7/CSV',
    },
  ],
  'fraud-detection': [
    {
      id: 'transaction-history',
      name: 'Transaction History',
      description: 'Historical payment transactions with fraud labels',
      records: '50M transactions',
      size: '25.8 GB',
      format: 'Parquet',
    },
    {
      id: 'customer-profiles',
      name: 'Customer Profiles',
      description: 'Account holder demographics and behavior patterns',
      records: '2.5M profiles',
      size: '3.7 GB',
      format: 'JSON/CSV',
    },
    {
      id: 'device-fingerprints',
      name: 'Device Fingerprints',
      description: 'Device metadata and authentication patterns',
      records: '8.7M devices',
      size: '2.1 GB',
      format: 'JSON',
    },
    {
      id: 'merchant-data',
      name: 'Merchant Data',
      description: 'Merchant categories, risk scores, and transaction patterns',
      records: '450K merchants',
      size: '980 MB',
      format: 'CSV',
    },
  ],
  'predictive-maintenance': [
    {
      id: 'iot-telemetry',
      name: 'IoT Sensor Telemetry',
      description: 'Real-time sensor data from manufacturing equipment',
      records: '10M readings',
      size: '15.2 GB',
      format: 'Time-series',
    },
    {
      id: 'maintenance-logs',
      name: 'Maintenance Logs',
      description: 'Historical maintenance records and failure events',
      records: '85K records',
      size: '2.3 GB',
      format: 'JSON/CSV',
    },
    {
      id: 'equipment-specs',
      name: 'Equipment Specifications',
      description: 'Technical specifications and operating parameters',
      records: '1,250 assets',
      size: '450 MB',
      format: 'XML/JSON',
    },
    {
      id: 'failure-patterns',
      name: 'Failure Pattern Analysis',
      description: 'ML-ready failure mode and effects analysis data',
      records: '23K patterns',
      size: '1.1 GB',
      format: 'Parquet',
    },
  ],
  'renewable-optimization': [
    {
      id: 'generation-data',
      name: 'Generation Data',
      description: 'Historical renewable energy generation patterns',
      records: '8.7M readings',
      size: '12.4 GB',
      format: 'Time-series',
    },
    {
      id: 'weather-forecast',
      name: 'Weather Forecast Data',
      description: 'High-resolution weather predictions for renewable sites',
      records: '365 days',
      size: '5.8 GB',
      format: 'GRIB2/NetCDF',
    },
    {
      id: 'grid-demand',
      name: 'Grid Demand Patterns',
      description: 'Historical and predicted electricity demand curves',
      records: '5 years',
      size: '3.2 GB',
      format: 'CSV/JSON',
    },
    {
      id: 'storage-metrics',
      name: 'Battery Storage Metrics',
      description: 'Charge/discharge cycles and efficiency data',
      records: '450K cycles',
      size: '1.9 GB',
      format: 'HDF5',
    },
  ],
  'drilling-risk': [
    {
      id: 'drilling-logs',
      name: 'Drilling Logs',
      description: 'Real-time drilling parameters and mud logs',
      records: '850 wells',
      size: '18.5 GB',
      format: 'LAS/WITSML',
    },
    {
      id: 'seismic-data',
      name: 'Seismic Survey Data',
      description: '3D seismic volumes and interpretation',
      records: '125 surveys',
      size: '45.2 GB',
      format: 'SEG-Y',
    },
    {
      id: 'offset-wells',
      name: 'Offset Well Analysis',
      description: 'Nearby well performance and drilling hazards',
      records: '3,200 wells',
      size: '7.8 GB',
      format: 'CSV/JSON',
    },
    {
      id: 'formation-pressure',
      name: 'Formation Pressure Data',
      description: 'Pore pressure and fracture gradient models',
      records: '15K data points',
      size: '2.1 GB',
      format: 'LAS/CSV',
    },
  ],
  'environmental-compliance': [
    {
      id: 'emissions-monitoring',
      name: 'Emissions Monitoring',
      description: 'Continuous emissions monitoring system data',
      records: '24/7 monitoring',
      size: '9.3 GB',
      format: 'Time-series',
    },
    {
      id: 'regulatory-database',
      name: 'Regulatory Database',
      description: 'Federal and state environmental regulations',
      records: '3,400+ rules',
      size: '1.2 GB',
      format: 'JSON/XML',
    },
    {
      id: 'inspection-reports',
      name: 'Inspection Reports',
      description: 'Historical compliance inspection results',
      records: '12K reports',
      size: '3.5 GB',
      format: 'PDF/JSON',
    },
    {
      id: 'satellite-imagery',
      name: 'Satellite Imagery',
      description: 'Multispectral imagery for leak detection',
      records: 'Weekly captures',
      size: '28.7 GB',
      format: 'GeoTIFF',
    },
  ],
  'load-forecasting': [
    {
      id: 'smart-meter-data',
      name: 'Smart Meter Data',
      description: 'Granular consumption data from AMI systems',
      records: '5M meters',
      size: '32.1 GB',
      format: 'Parquet',
    },
    {
      id: 'weather-history',
      name: 'Weather History',
      description: 'Temperature, humidity, and solar irradiance',
      records: '10 years',
      size: '4.7 GB',
      format: 'NetCDF',
    },
    {
      id: 'economic-indicators',
      name: 'Economic Indicators',
      description: 'GDP, employment, and industrial production',
      records: 'Monthly data',
      size: '890 MB',
      format: 'CSV/JSON',
    },
    {
      id: 'ev-adoption',
      name: 'EV Adoption Data',
      description: 'Electric vehicle registration and charging patterns',
      records: '2.3M vehicles',
      size: '1.8 GB',
      format: 'JSON',
    },
  ],
  'phmsa-compliance': [
    {
      id: 'pipeline-attributes',
      name: 'Pipeline Attributes',
      description: 'Physical characteristics and operating conditions',
      records: '195K miles',
      size: '5.2 GB',
      format: 'GIS/CSV',
    },
    {
      id: 'inspection-data',
      name: 'Inspection Data',
      description: 'ILI runs, direct assessment, and pressure tests',
      records: '45K inspections',
      size: '12.8 GB',
      format: 'XML/JSON',
    },
    {
      id: 'incident-history',
      name: 'Incident History',
      description: '20-year incident and near-miss database',
      records: '8,500 events',
      size: '2.3 GB',
      format: 'CSV',
    },
    {
      id: 'regulatory-filings',
      name: 'Regulatory Filings',
      description: 'Annual reports and operator submissions',
      records: '10 years',
      size: '3.9 GB',
      format: 'PDF/XML',
    },
  ],
  'methane-detection': [
    {
      id: 'sensor-network',
      name: 'Sensor Network Data',
      description: 'Fixed methane sensor continuous monitoring',
      records: '850 sensors',
      size: '7.2 GB',
      format: 'Time-series',
    },
    {
      id: 'aerial-surveys',
      name: 'Aerial Survey Data',
      description: 'Drone and aircraft-based detection results',
      records: 'Monthly flights',
      size: '15.3 GB',
      format: 'LAS/GeoTIFF',
    },
    {
      id: 'satellite-methane',
      name: 'Satellite Methane Data',
      description: 'TROPOMI and GHGSat observations',
      records: 'Daily passes',
      size: '8.9 GB',
      format: 'NetCDF/HDF5',
    },
    {
      id: 'leak-repair-logs',
      name: 'Leak Repair Logs',
      description: 'Historical leak locations and repair actions',
      records: '23K repairs',
      size: '1.4 GB',
      format: 'JSON/CSV',
    },
  ],
  'grid-resilience': [
    {
      id: 'asset-condition',
      name: 'Asset Condition Data',
      description: 'Equipment health scores and failure probabilities',
      records: '125K assets',
      size: '6.8 GB',
      format: 'JSON/CSV',
    },
    {
      id: 'vegetation-management',
      name: 'Vegetation Management',
      description: 'LiDAR surveys and trimming schedules',
      records: '50K miles',
      size: '22.4 GB',
      format: 'LAS/SHP',
    },
    {
      id: 'storm-impact',
      name: 'Storm Impact Models',
      description: 'Historical storm damage and restoration data',
      records: '500+ events',
      size: '4.2 GB',
      format: 'GeoJSON',
    },
    {
      id: 'crew-resources',
      name: 'Crew Resource Data',
      description: 'Restoration crew locations and capabilities',
      records: '2,500 crews',
      size: '980 MB',
      format: 'JSON',
    },
  ],
  'internal-audit': [
    {
      id: 'control-framework',
      name: 'Control Framework',
      description: 'SOX controls and testing procedures',
      records: '1,200 controls',
      size: '450 MB',
      format: 'XLSX/JSON',
    },
    {
      id: 'transaction-logs',
      name: 'Transaction Logs',
      description: 'Financial and operational transaction data',
      records: '50M records',
      size: '18.7 GB',
      format: 'Parquet',
    },
    {
      id: 'access-logs',
      name: 'System Access Logs',
      description: 'User access and privilege changes',
      records: '12M events',
      size: '3.2 GB',
      format: 'JSON',
    },
    {
      id: 'audit-workpapers',
      name: 'Audit Workpapers',
      description: 'Historical audit findings and remediation',
      records: '5 years',
      size: '2.8 GB',
      format: 'PDF/DOCX',
    },
  ],
  'scada-integration': [
    {
      id: 'protocol-library',
      name: 'Protocol Library',
      description: 'SCADA protocol definitions and mappings',
      records: '200+ protocols',
      size: '890 MB',
      format: 'XML/JSON',
    },
    {
      id: 'point-database',
      name: 'Point Database',
      description: 'SCADA point configurations and metadata',
      records: '2.5M points',
      size: '4.3 GB',
      format: 'CSV/JSON',
    },
    {
      id: 'historian-data',
      name: 'Historian Data',
      description: 'Historical SCADA values and events',
      records: '5 years',
      size: '45.8 GB',
      format: 'Time-series',
    },
    {
      id: 'network-topology',
      name: 'Network Topology',
      description: 'SCADA network architecture and security zones',
      records: '850 devices',
      size: '1.2 GB',
      format: 'GraphML',
    },
  ],
  'predictive-resilience': [
    {
      id: 'grid-topology',
      name: 'Grid Topology Model',
      description: 'Detailed electrical network connectivity',
      records: '500K nodes',
      size: '8.9 GB',
      format: 'CIM/XML',
    },
    {
      id: 'contingency-analysis',
      name: 'Contingency Analysis',
      description: 'N-1 and N-2 contingency scenarios',
      records: '10K scenarios',
      size: '3.4 GB',
      format: 'JSON',
    },
    {
      id: 'der-registry',
      name: 'DER Registry',
      description: 'Distributed energy resource capabilities',
      records: '125K resources',
      size: '2.1 GB',
      format: 'CSV/JSON',
    },
    {
      id: 'load-flexibility',
      name: 'Load Flexibility Data',
      description: 'Demand response and flexible load profiles',
      records: '2.3M customers',
      size: '5.7 GB',
      format: 'Parquet',
    },
  ],
  'cyber-defense': [
    {
      id: 'network-traffic',
      name: 'Network Traffic Logs',
      description: 'Deep packet inspection and flow data',
      records: '90 days',
      size: '125.3 GB',
      format: 'PCAP/JSON',
    },
    {
      id: 'threat-intelligence',
      name: 'Threat Intelligence',
      description: 'IOCs, TTPs, and threat actor profiles',
      records: 'Real-time feeds',
      size: '2.8 GB',
      format: 'STIX/JSON',
    },
    {
      id: 'vulnerability-scans',
      name: 'Vulnerability Scans',
      description: 'Infrastructure vulnerability assessment results',
      records: 'Weekly scans',
      size: '4.5 GB',
      format: 'XML/JSON',
    },
    {
      id: 'incident-response',
      name: 'Incident Response Data',
      description: 'Historical incidents and remediation actions',
      records: '3,200 incidents',
      size: '1.9 GB',
      format: 'JSON',
    },
  ],
  'wildfire-prevention': [
    {
      id: 'vegetation-lidar',
      name: 'Vegetation LiDAR',
      description: 'High-resolution vegetation encroachment data',
      records: '125K miles',
      size: '78.4 GB',
      format: 'LAS/LAZ',
    },
    {
      id: 'weather-stations',
      name: 'Weather Station Network',
      description: 'Microclimate data from utility weather stations',
      records: '2,500 stations',
      size: '5.2 GB',
      format: 'CSV/JSON',
    },
    {
      id: 'fire-history',
      name: 'Fire History Database',
      description: 'Historical wildfire perimeters and causes',
      records: '20 years',
      size: '3.8 GB',
      format: 'GeoJSON/SHP',
    },
    {
      id: 'equipment-inspections',
      name: 'Equipment Inspections',
      description: 'Detailed inspection reports and imagery',
      records: '450K assets',
      size: '32.1 GB',
      format: 'JSON/JPEG',
    },
  ],
  'clinical-trial-matching': [
    {
      id: 'trial-registry',
      name: 'Clinical Trial Registry',
      description: 'Active trials with eligibility criteria',
      records: '45K trials',
      size: '2.3 GB',
      format: 'XML/JSON',
    },
    {
      id: 'patient-registry',
      name: 'Patient Registry',
      description: 'De-identified patient profiles for matching',
      records: '1.2M patients',
      size: '8.7 GB',
      format: 'FHIR',
    },
    {
      id: 'genomic-data',
      name: 'Genomic Data',
      description: 'Genetic markers and mutation profiles',
      records: '250K profiles',
      size: '15.4 GB',
      format: 'VCF/JSON',
    },
    {
      id: 'site-performance',
      name: 'Site Performance Data',
      description: 'Trial site metrics and enrollment history',
      records: '8,500 sites',
      size: '1.1 GB',
      format: 'CSV',
    },
  ],
  'treatment-recommendation': [
    {
      id: 'clinical-guidelines',
      name: 'Clinical Guidelines',
      description: 'Evidence-based treatment protocols',
      records: '12K guidelines',
      size: '3.4 GB',
      format: 'JSON/PDF',
    },
    {
      id: 'drug-database',
      name: 'Drug Database',
      description: 'Medication profiles and interactions',
      records: '25K drugs',
      size: '890 MB',
      format: 'JSON',
    },
    {
      id: 'outcome-data',
      name: 'Treatment Outcomes',
      description: 'Historical treatment effectiveness data',
      records: '5M cases',
      size: '12.8 GB',
      format: 'Parquet',
    },
    {
      id: 'biomarker-panels',
      name: 'Biomarker Panels',
      description: 'Diagnostic markers and treatment response',
      records: '450 panels',
      size: '2.1 GB',
      format: 'CSV/JSON',
    },
  ],
  'diagnosis-assistant': [
    {
      id: 'symptom-database',
      name: 'Symptom Database',
      description: 'Symptom-disease associations and probabilities',
      records: '50K symptoms',
      size: '1.8 GB',
      format: 'JSON',
    },
    {
      id: 'medical-imaging',
      name: 'Medical Imaging Library',
      description: 'Annotated diagnostic images',
      records: '2.5M images',
      size: '125.7 GB',
      format: 'DICOM/PNG',
    },
    {
      id: 'lab-reference',
      name: 'Lab Reference Ranges',
      description: 'Normal and abnormal lab value ranges',
      records: '15K tests',
      size: '450 MB',
      format: 'CSV',
    },
    {
      id: 'case-studies',
      name: 'Clinical Case Studies',
      description: 'Documented cases with confirmed diagnoses',
      records: '850K cases',
      size: '6.3 GB',
      format: 'JSON',
    },
  ],
  'medical-supply-chain': [
    {
      id: 'inventory-levels',
      name: 'Inventory Levels',
      description: 'Real-time stock levels across facilities',
      records: '125K SKUs',
      size: '3.2 GB',
      format: 'JSON',
    },
    {
      id: 'supplier-catalog',
      name: 'Supplier Catalog',
      description: 'Product catalogs and lead times',
      records: '2,500 suppliers',
      size: '1.9 GB',
      format: 'CSV/JSON',
    },
    {
      id: 'usage-patterns',
      name: 'Usage Patterns',
      description: 'Historical consumption and demand data',
      records: '5 years',
      size: '8.4 GB',
      format: 'Parquet',
    },
    {
      id: 'recall-database',
      name: 'Recall Database',
      description: 'Product recalls and safety alerts',
      records: '12K recalls',
      size: '890 MB',
      format: 'JSON',
    },
  ],
  'ai-credit-scoring': [
    {
      id: 'credit-histories',
      name: 'Credit Histories',
      description: 'Traditional credit bureau data',
      records: '10M profiles',
      size: '45.2 GB',
      format: 'Parquet',
    },
    {
      id: 'alternative-data',
      name: 'Alternative Data',
      description: 'Utility payments, rent, and mobile data',
      records: '25M records',
      size: '18.7 GB',
      format: 'JSON/CSV',
    },
    {
      id: 'default-history',
      name: 'Default History',
      description: 'Loan performance and default patterns',
      records: '5M loans',
      size: '12.3 GB',
      format: 'Parquet',
    },
    {
      id: 'economic-context',
      name: 'Economic Context',
      description: 'Macroeconomic indicators by region',
      records: '10 years',
      size: '2.1 GB',
      format: 'CSV',
    },
  ],
  'portfolio-optimization': [
    {
      id: 'market-data',
      name: 'Market Data',
      description: 'Historical prices, volumes, and volatility',
      records: '20 years',
      size: '78.5 GB',
      format: 'Parquet',
    },
    {
      id: 'fundamental-data',
      name: 'Fundamental Data',
      description: 'Company financials and ratios',
      records: '15K companies',
      size: '12.3 GB',
      format: 'JSON',
    },
    {
      id: 'alternative-datasets',
      name: 'Alternative Datasets',
      description: 'Satellite, sentiment, and web data',
      records: 'Real-time',
      size: '25.8 GB',
      format: 'JSON/Parquet',
    },
    {
      id: 'risk-factors',
      name: 'Risk Factor Models',
      description: 'Factor exposures and correlations',
      records: '500 factors',
      size: '3.4 GB',
      format: 'HDF5',
    },
  ],
  'aml-monitoring': [
    {
      id: 'transaction-network',
      name: 'Transaction Network',
      description: 'Money flow patterns and relationships',
      records: '500M edges',
      size: '125.8 GB',
      format: 'GraphML',
    },
    {
      id: 'kyc-data',
      name: 'KYC Data',
      description: 'Customer identification and verification',
      records: '25M profiles',
      size: '32.1 GB',
      format: 'JSON',
    },
    {
      id: 'sanctions-lists',
      name: 'Sanctions Lists',
      description: 'Global sanctions and PEP databases',
      records: 'Daily updates',
      size: '2.8 GB',
      format: 'JSON/CSV',
    },
    {
      id: 'sar-history',
      name: 'SAR History',
      description: 'Suspicious activity reports and outcomes',
      records: '450K reports',
      size: '5.6 GB',
      format: 'JSON',
    },
  ],
  'insurance-risk': [
    {
      id: 'claims-history',
      name: 'Claims History',
      description: 'Historical claims with loss amounts',
      records: '15M claims',
      size: '28.4 GB',
      format: 'Parquet',
    },
    {
      id: 'telematics-data',
      name: 'Telematics Data',
      description: 'IoT device data for usage-based insurance',
      records: '2.5M devices',
      size: '45.7 GB',
      format: 'Time-series',
    },
    {
      id: 'catastrophe-models',
      name: 'Catastrophe Models',
      description: 'Natural disaster risk assessments',
      records: '10K scenarios',
      size: '8.9 GB',
      format: 'NetCDF',
    },
    {
      id: 'fraud-indicators',
      name: 'Fraud Indicators',
      description: 'Known fraud patterns and red flags',
      records: '125K patterns',
      size: '1.8 GB',
      format: 'JSON',
    },
  ],
  'quality-inspection': [
    {
      id: 'defect-images',
      name: 'Defect Image Library',
      description: 'Annotated images of product defects',
      records: '2.5M images',
      size: '85.3 GB',
      format: 'JPEG/PNG',
    },
    {
      id: 'sensor-readings',
      name: 'Quality Sensor Data',
      description: 'Inline sensor measurements',
      records: '100M readings',
      size: '32.1 GB',
      format: 'Time-series',
    },
    {
      id: 'inspection-logs',
      name: 'Inspection Logs',
      description: 'Manual inspection results and notes',
      records: '450K inspections',
      size: '3.2 GB',
      format: 'JSON/CSV',
    },
    {
      id: 'rework-data',
      name: 'Rework Data',
      description: 'Defect types and remediation actions',
      records: '85K records',
      size: '890 MB',
      format: 'CSV',
    },
  ],
  'supply-chain': [
    {
      id: 'supplier-network',
      name: 'Supplier Network',
      description: 'Multi-tier supplier relationships',
      records: '125K suppliers',
      size: '4.5 GB',
      format: 'GraphML/JSON',
    },
    {
      id: 'shipment-tracking',
      name: 'Shipment Tracking',
      description: 'Real-time location and status data',
      records: '5M shipments',
      size: '18.7 GB',
      format: 'JSON',
    },
    {
      id: 'demand-signals',
      name: 'Demand Signals',
      description: 'POS data and demand forecasts',
      records: '10K SKUs',
      size: '12.3 GB',
      format: 'Parquet',
    },
  ],
  'demand-forecasting': [
    {
      id: 'pos-data',
      name: 'Point of Sale Data',
      description: 'Historical sales transactions by SKU',
      records: '500M transactions',
      size: '125.8 GB',
      format: 'Parquet',
    },
    {
      id: 'inventory-levels',
      name: 'Inventory Levels',
      description: 'Stock levels across locations',
      records: '50K SKUs',
      size: '8.7 GB',
      format: 'JSON',
    },
    {
      id: 'promotion-calendar',
      name: 'Promotion Calendar',
      description: 'Historical and planned promotions',
      records: '5 years',
      size: '1.2 GB',
      format: 'CSV',
    },
    {
      id: 'external-factors',
      name: 'External Factors',
      description: 'Weather, events, and economic data',
      records: 'Daily updates',
      size: '3.4 GB',
      format: 'JSON',
    },
  ],
  'customer-personalization': [
    {
      id: 'browsing-behavior',
      name: 'Browsing Behavior',
      description: 'Clickstream and session data',
      records: '100M sessions',
      size: '85.3 GB',
      format: 'Parquet',
    },
    {
      id: 'purchase-history',
      name: 'Purchase History',
      description: 'Transaction history with product details',
      records: '50M orders',
      size: '32.1 GB',
      format: 'JSON',
    },
    {
      id: 'customer-attributes',
      name: 'Customer Attributes',
      description: 'Demographics and preferences',
      records: '10M customers',
      size: '4.5 GB',
      format: 'CSV',
    },
    {
      id: 'product-catalog',
      name: 'Product Catalog',
      description: 'Product attributes and relationships',
      records: '2M products',
      size: '2.8 GB',
      format: 'JSON',
    },
  ],
  'price-optimization': [
    {
      id: 'price-history',
      name: 'Price History',
      description: 'Historical prices and elasticity',
      records: '5 years',
      size: '12.3 GB',
      format: 'Parquet',
    },
    {
      id: 'competitor-prices',
      name: 'Competitor Prices',
      description: 'Competitive pricing intelligence',
      records: 'Real-time',
      size: '5.8 GB',
      format: 'JSON',
    },
    {
      id: 'cost-data',
      name: 'Cost Data',
      description: 'Product costs and margins',
      records: '100K SKUs',
      size: '1.9 GB',
      format: 'CSV',
    },
    {
      id: 'demand-curves',
      name: 'Demand Curves',
      description: 'Price-demand relationships',
      records: '50K products',
      size: '890 MB',
      format: 'JSON',
    },
  ],
  'route-optimization': [
    {
      id: 'delivery-history',
      name: 'Delivery History',
      description: 'Historical routes and performance',
      records: '10M deliveries',
      size: '28.4 GB',
      format: 'Parquet',
    },
    {
      id: 'traffic-patterns',
      name: 'Traffic Patterns',
      description: 'Real-time and historical traffic data',
      records: '365 days',
      size: '15.7 GB',
      format: 'JSON',
    },
    {
      id: 'vehicle-telemetry',
      name: 'Vehicle Telemetry',
      description: 'Fleet tracking and performance data',
      records: '5K vehicles',
      size: '8.9 GB',
      format: 'Time-series',
    },
    {
      id: 'customer-locations',
      name: 'Customer Locations',
      description: 'Delivery addresses and preferences',
      records: '2M addresses',
      size: '3.2 GB',
      format: 'GeoJSON',
    },
  ],
  'fleet-maintenance': [
    {
      id: 'vehicle-diagnostics',
      name: 'Vehicle Diagnostics',
      description: 'OBD-II and telematics data',
      records: '15M readings',
      size: '22.5 GB',
      format: 'Time-series',
    },
    {
      id: 'maintenance-records',
      name: 'Maintenance Records',
      description: 'Service history and repairs',
      records: '250K services',
      size: '4.8 GB',
      format: 'JSON',
    },
    {
      id: 'parts-inventory',
      name: 'Parts Inventory',
      description: 'Spare parts availability and costs',
      records: '50K parts',
      size: '1.2 GB',
      format: 'CSV',
    },
    {
      id: 'driver-behavior',
      name: 'Driver Behavior',
      description: 'Driving patterns affecting wear',
      records: '10K drivers',
      size: '6.3 GB',
      format: 'JSON',
    },
  ],
  'warehouse-automation': [
    {
      id: 'wms-data',
      name: 'WMS Data',
      description: 'Warehouse management system logs',
      records: '100M events',
      size: '45.8 GB',
      format: 'JSON',
    },
    {
      id: 'robot-telemetry',
      name: 'Robot Telemetry',
      description: 'AGV and robot performance data',
      records: '500 robots',
      size: '18.2 GB',
      format: 'Time-series',
    },
    {
      id: 'pick-pack-data',
      name: 'Pick & Pack Data',
      description: 'Order fulfillment metrics',
      records: '25M orders',
      size: '12.7 GB',
      format: 'Parquet',
    },
    {
      id: 'layout-optimization',
      name: 'Layout Optimization',
      description: 'Warehouse layout and slotting data',
      records: '100K locations',
      size: '2.3 GB',
      format: 'JSON',
    },
  ],
  'adaptive-learning': [
    {
      id: 'student-interactions',
      name: 'Student Interactions',
      description: 'Learning platform engagement data',
      records: '50M interactions',
      size: '32.1 GB',
      format: 'Parquet',
    },
    {
      id: 'assessment-results',
      name: 'Assessment Results',
      description: 'Quiz and test performance data',
      records: '10M assessments',
      size: '8.4 GB',
      format: 'JSON',
    },
    {
      id: 'content-library',
      name: 'Content Library',
      description: 'Educational materials and metadata',
      records: '500K items',
      size: '15.7 GB',
      format: 'JSON',
    },
    {
      id: 'learning-paths',
      name: 'Learning Paths',
      description: 'Curriculum sequences and prerequisites',
      records: '10K paths',
      size: '890 MB',
      format: 'JSON',
    },
  ],
  'student-performance': [
    {
      id: 'academic-records',
      name: 'Academic Records',
      description: 'Grades, attendance, and progress',
      records: '2M students',
      size: '12.3 GB',
      format: 'CSV',
    },
    {
      id: 'engagement-metrics',
      name: 'Engagement Metrics',
      description: 'Platform usage and participation',
      records: '100M events',
      size: '28.5 GB',
      format: 'Parquet',
    },
    {
      id: 'demographic-data',
      name: 'Demographic Data',
      description: 'Student background information',
      records: '2M profiles',
      size: '3.2 GB',
      format: 'JSON',
    },
    {
      id: 'intervention-history',
      name: 'Intervention History',
      description: 'Support services and outcomes',
      records: '500K interventions',
      size: '1.8 GB',
      format: 'CSV',
    },
  ],
  'content-recommendation': [
    {
      id: 'content-metadata',
      name: 'Content Metadata',
      description: 'Learning resource attributes',
      records: '10M resources',
      size: '18.7 GB',
      format: 'JSON',
    },
    {
      id: 'usage-analytics',
      name: 'Usage Analytics',
      description: 'Content consumption patterns',
      records: '500M views',
      size: '85.3 GB',
      format: 'Parquet',
    },
    {
      id: 'learning-outcomes',
      name: 'Learning Outcomes',
      description: 'Content effectiveness metrics',
      records: '50M outcomes',
      size: '22.4 GB',
      format: 'JSON',
    },
    {
      id: 'user-feedback',
      name: 'User Feedback',
      description: 'Ratings and reviews',
      records: '5M reviews',
      size: '2.1 GB',
      format: 'CSV',
    },
  ],
  'drug-discovery': [
    {
      id: 'molecular-library',
      name: 'Molecular Library',
      description: 'Chemical structures and properties',
      records: '100M compounds',
      size: '125.8 GB',
      format: 'SDF/JSON',
    },
    {
      id: 'bioassay-data',
      name: 'Bioassay Data',
      description: 'Screening results and IC50 values',
      records: '50M assays',
      size: '45.2 GB',
      format: 'CSV',
    },
    {
      id: 'protein-structures',
      name: 'Protein Structures',
      description: '3D structures and binding sites',
      records: '200K proteins',
      size: '32.1 GB',
      format: 'PDB/mmCIF',
    },
    {
      id: 'clinical-outcomes',
      name: 'Clinical Outcomes',
      description: 'Trial results and adverse events',
      records: '100K trials',
      size: '8.9 GB',
      format: 'JSON',
    },
  ],
  'clinical-trial-optimization': [
    {
      id: 'protocol-database',
      name: 'Protocol Database',
      description: 'Trial protocols and amendments',
      records: '50K protocols',
      size: '4.5 GB',
      format: 'XML/JSON',
    },
    {
      id: 'site-metrics',
      name: 'Site Performance Metrics',
      description: 'Enrollment and quality data',
      records: '10K sites',
      size: '2.8 GB',
      format: 'CSV',
    },
    {
      id: 'patient-journey',
      name: 'Patient Journey Data',
      description: 'Recruitment to completion tracking',
      records: '500K patients',
      size: '6.7 GB',
      format: 'JSON',
    },
    {
      id: 'regulatory-timelines',
      name: 'Regulatory Timelines',
      description: 'Approval processes and durations',
      records: '25K submissions',
      size: '1.2 GB',
      format: 'CSV',
    },
  ],
  'adverse-event': [
    {
      id: 'safety-reports',
      name: 'Safety Reports',
      description: 'Adverse event case reports',
      records: '2M reports',
      size: '15.3 GB',
      format: 'E2B/JSON',
    },
    {
      id: 'social-media',
      name: 'Social Media Monitoring',
      description: 'Patient-reported outcomes',
      records: '50M posts',
      size: '28.7 GB',
      format: 'JSON',
    },
    {
      id: 'literature-mining',
      name: 'Literature Mining',
      description: 'Published safety signals',
      records: '10M articles',
      size: '12.4 GB',
      format: 'XML',
    },
    {
      id: 'signal-database',
      name: 'Signal Database',
      description: 'Validated safety signals',
      records: '100K signals',
      size: '3.2 GB',
      format: 'JSON',
    },
  ],
  'emergency-response': [
    {
      id: 'incident-data',
      name: 'Incident Data',
      description: 'Emergency call and dispatch logs',
      records: '5M incidents',
      size: '18.5 GB',
      format: 'JSON',
    },
    {
      id: 'resource-inventory',
      name: 'Resource Inventory',
      description: 'Personnel and equipment availability',
      records: '50K resources',
      size: '2.3 GB',
      format: 'CSV',
    },
    {
      id: 'gis-layers',
      name: 'GIS Layers',
      description: 'Infrastructure and hazard maps',
      records: '1K layers',
      size: '45.8 GB',
      format: 'GeoJSON/SHP',
    },
    {
      id: 'weather-alerts',
      name: 'Weather Alerts',
      description: 'Real-time weather warnings',
      records: 'Live feed',
      size: '890 MB',
      format: 'JSON',
    },
  ],
  'infrastructure-coordination': [
    {
      id: 'asset-registry',
      name: 'Critical Asset Registry',
      description: 'Infrastructure dependencies',
      records: '500K assets',
      size: '8.9 GB',
      format: 'JSON',
    },
    {
      id: 'threat-intelligence',
      name: 'Threat Intelligence',
      description: 'Security threats and vulnerabilities',
      records: 'Real-time',
      size: '3.4 GB',
      format: 'STIX',
    },
    {
      id: 'outage-data',
      name: 'Outage Data',
      description: 'Service disruption history',
      records: '100K events',
      size: '5.2 GB',
      format: 'JSON',
    },
    {
      id: 'recovery-plans',
      name: 'Recovery Plans',
      description: 'Disaster recovery procedures',
      records: '5K plans',
      size: '1.8 GB',
      format: 'PDF/JSON',
    },
  ],
  'citizen-services': [
    {
      id: 'service-catalog',
      name: 'Service Catalog',
      description: 'Government services directory',
      records: '10K services',
      size: '890 MB',
      format: 'JSON',
    },
    {
      id: 'citizen-profiles',
      name: 'Citizen Profiles',
      description: 'Anonymized demographic data',
      records: '50M citizens',
      size: '32.1 GB',
      format: 'Parquet',
    },
    {
      id: 'transaction-logs',
      name: 'Transaction Logs',
      description: 'Service usage history',
      records: '100M transactions',
      size: '45.7 GB',
      format: 'JSON',
    },
    {
      id: 'feedback-data',
      name: 'Feedback Data',
      description: 'Citizen satisfaction surveys',
      records: '5M responses',
      size: '2.3 GB',
      format: 'CSV',
    },
  ],
  'public-safety': [
    {
      id: 'crime-data',
      name: 'Crime Data',
      description: 'Incident reports and patterns',
      records: '10M incidents',
      size: '15.8 GB',
      format: 'JSON',
    },
    {
      id: 'patrol-data',
      name: 'Patrol Data',
      description: 'Officer locations and activities',
      records: '50M events',
      size: '22.3 GB',
      format: 'Time-series',
    },
    {
      id: 'camera-network',
      name: 'Camera Network',
      description: 'Video analytics metadata',
      records: '10K cameras',
      size: '125.4 GB',
      format: 'JSON',
    },
    {
      id: 'community-data',
      name: 'Community Data',
      description: 'Demographics and social factors',
      records: '5K neighborhoods',
      size: '3.2 GB',
      format: 'GeoJSON',
    },
  ],
  'resource-optimization': [
    {
      id: 'budget-data',
      name: 'Budget Data',
      description: 'Government spending by department',
      records: '10 years',
      size: '8.7 GB',
      format: 'CSV',
    },
    {
      id: 'performance-metrics',
      name: 'Performance Metrics',
      description: 'Program effectiveness measures',
      records: '50K programs',
      size: '4.2 GB',
      format: 'JSON',
    },
    {
      id: 'procurement-data',
      name: 'Procurement Data',
      description: 'Contracts and vendor performance',
      records: '500K contracts',
      size: '12.3 GB',
      format: 'JSON',
    },
    {
      id: 'audit-findings',
      name: 'Audit Findings',
      description: 'Waste and inefficiency reports',
      records: '25K audits',
      size: '2.8 GB',
      format: 'PDF/JSON',
    },
  ],
  'network-performance': [
    {
      id: 'network-metrics',
      name: 'Network Metrics',
      description: 'Latency, throughput, and packet loss',
      records: '100B events',
      size: '250.8 GB',
      format: 'Time-series',
    },
    {
      id: 'topology-data',
      name: 'Network Topology',
      description: 'Infrastructure and routing tables',
      records: '1M devices',
      size: '15.3 GB',
      format: 'GraphML',
    },
    {
      id: 'traffic-patterns',
      name: 'Traffic Patterns',
      description: 'Application and user behavior',
      records: '50TB daily',
      size: '125.7 GB',
      format: 'NetFlow',
    },
    {
      id: 'fault-history',
      name: 'Fault History',
      description: 'Outages and root causes',
      records: '100K incidents',
      size: '5.8 GB',
      format: 'JSON',
    },
  ],
  'churn-prevention': [
    {
      id: 'customer-behavior',
      name: 'Customer Behavior',
      description: 'Usage patterns and engagement',
      records: '50M customers',
      size: '85.4 GB',
      format: 'Parquet',
    },
    {
      id: 'billing-data',
      name: 'Billing Data',
      description: 'Payment history and disputes',
      records: '500M records',
      size: '125.8 GB',
      format: 'CSV',
    },
    {
      id: 'support-tickets',
      name: 'Support Tickets',
      description: 'Customer service interactions',
      records: '25M tickets',
      size: '18.7 GB',
      format: 'JSON',
    },
    {
      id: 'competitor-offers',
      name: 'Competitor Offers',
      description: 'Market intelligence data',
      records: 'Real-time',
      size: '2.3 GB',
      format: 'JSON',
    },
  ],
  'network-security': [
    {
      id: 'security-logs',
      name: 'Security Logs',
      description: 'Firewall and IDS/IPS events',
      records: '1T events',
      size: '500.8 GB',
      format: 'JSON/Syslog',
    },
    {
      id: 'threat-feeds',
      name: 'Threat Intelligence Feeds',
      description: 'IOCs and attack patterns',
      records: 'Real-time',
      size: '8.9 GB',
      format: 'STIX/JSON',
    },
    {
      id: 'vulnerability-data',
      name: 'Vulnerability Data',
      description: 'CVEs and patch status',
      records: '500K vulns',
      size: '3.2 GB',
      format: 'JSON',
    },
    {
      id: 'incident-database',
      name: 'Incident Database',
      description: 'Security breach history',
      records: '50K incidents',
      size: '5.4 GB',
      format: 'JSON',
    },
  ],
  'cross-industry-analytics': [
    {
      id: 'industry-metrics',
      name: 'Industry Metrics',
      description: 'KPIs across all verticals',
      records: '10K metrics',
      size: '45.8 GB',
      format: 'Parquet',
    },
    {
      id: 'best-practices',
      name: 'Best Practices Database',
      description: 'Successful patterns and methods',
      records: '50K practices',
      size: '8.7 GB',
      format: 'JSON',
    },
    {
      id: 'innovation-catalog',
      name: 'Innovation Catalog',
      description: 'Cross-industry innovations',
      records: '25K innovations',
      size: '3.2 GB',
      format: 'JSON',
    },
    {
      id: 'benchmark-data',
      name: 'Benchmark Data',
      description: 'Performance comparisons',
      records: '1M benchmarks',
      size: '12.4 GB',
      format: 'CSV',
    },
  ],
  'universal-compliance': [
    {
      id: 'regulation-database',
      name: 'Global Regulations',
      description: 'Laws and regulations worldwide',
      records: '500K regulations',
      size: '25.8 GB',
      format: 'JSON/XML',
    },
    {
      id: 'compliance-mappings',
      name: 'Compliance Mappings',
      description: 'Requirement to control mappings',
      records: '10M mappings',
      size: '8.9 GB',
      format: 'JSON',
    },
    {
      id: 'audit-evidence',
      name: 'Audit Evidence',
      description: 'Compliance documentation',
      records: '100K documents',
      size: '45.7 GB',
      format: 'PDF/JSON',
    },
    {
      id: 'violation-history',
      name: 'Violation History',
      description: 'Past violations and remediation',
      records: '50K violations',
      size: '3.4 GB',
      format: 'JSON',
    },
  ],
  'multi-vertical-optimization': [
    {
      id: 'cross-vertical-patterns',
      name: 'Cross-Vertical Patterns',
      description: 'Transferable optimization patterns',
      records: '100K patterns',
      size: '15.8 GB',
      format: 'JSON',
    },
    {
      id: 'synergy-opportunities',
      name: 'Synergy Opportunities',
      description: 'Cross-industry collaboration data',
      records: '25K opportunities',
      size: '4.2 GB',
      format: 'JSON',
    },
    {
      id: 'resource-sharing',
      name: 'Resource Sharing Data',
      description: 'Shared resources across verticals',
      records: '50K resources',
      size: '2.8 GB',
      format: 'CSV',
    },
    {
      id: 'optimization-models',
      name: 'Optimization Models',
      description: 'Multi-objective optimization algorithms',
      records: '5K models',
      size: '8.9 GB',
      format: 'Python/JSON',
    },
  ],
  'industry-benchmarking': [
    {
      id: 'performance-data',
      name: 'Performance Data',
      description: 'Industry-wide performance metrics',
      records: '1M companies',
      size: '125.8 GB',
      format: 'Parquet',
    },
    {
      id: 'financial-benchmarks',
      name: 'Financial Benchmarks',
      description: 'Revenue, costs, and profitability',
      records: '10 years',
      size: '45.2 GB',
      format: 'CSV',
    },
    {
      id: 'operational-metrics',
      name: 'Operational Metrics',
      description: 'Efficiency and productivity data',
      records: '500K metrics',
      size: '18.7 GB',
      format: 'JSON',
    },
    {
      id: 'innovation-index',
      name: 'Innovation Index',
      description: 'R&D and patent data',
      records: '100K companies',
      size: '5.8 GB',
      format: 'JSON',
    },
  ],
};

export const DatasetCard: React.FC<{
  dataset: DatasetConfig;
  isLoaded: boolean;
  isLoading: boolean;
  onClick: () => void;
}> = ({ dataset, isLoaded, isLoading, onClick }) => {
  return (
    <div
      className={`bg-gray-800 border rounded-lg p-4 cursor-pointer transition-all ${
        isLoaded
          ? 'border-green-500 bg-green-900/20'
          : 'border-gray-700 hover:border-amber-500'
      }`}
      onClick={onClick}
    >
      <div className="flex items-start gap-3">
        {isLoading ? (
          <ArrowPathIcon className="h-6 w-6 text-amber-400 flex-shrink-0 animate-spin" />
        ) : isLoaded ? (
          <CheckCircleIcon className="h-6 w-6 text-green-400 flex-shrink-0" />
        ) : (
          <DocumentArrowDownIcon className="h-6 w-6 text-amber-400 flex-shrink-0" />
        )}
        <div className="flex-1">
          <h4 className="font-semibold text-white mb-1">{dataset.name}</h4>
          <p className="text-sm text-gray-400 mb-2">{dataset.description}</p>
          <div className="flex items-center gap-4 text-xs text-gray-500">
            <span>{dataset.records}</span>
            <span>•</span>
            <span>{dataset.size}</span>
            <span>•</span>
            <span>{dataset.format}</span>
          </div>
        </div>
      </div>
    </div>
  );
};