import { Agent } from '../vanguardAgents';

export const energyUtilitiesAgents: { [key: string]: Agent[] } = {
  'oilfield-lease': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Validate access permissions',
        'Audit trail generation',
        'Policy enforcement',
        'Compliance verification',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Cross-system data validation',
        'Consistency checks',
        'Master data synchronization',
        'Conflict resolution',
      ],
      connections: ['accuracy-agent', 'optimization-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Lease expiration detection',
        'Metadata correction',
        'Data quality scoring',
        'Anomaly detection',
      ],
      connections: ['optimization-agent', 'negotiation-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Portfolio analysis',
        'Financial modeling',
        'Risk assessment',
        'Renewal recommendations',
      ],
      connections: ['negotiation-agent'],
    },
    {
      id: 'negotiation-agent',
      name: 'Negotiation Vanguard',
      type: 'negotiation',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Contract analysis',
        'Clause extraction',
        'Package generation',
        'Terms optimization',
      ],
      connections: [],
    },
  ],

  'grid-anomaly': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'SCADA system authentication',
        'Cybersecurity threat monitoring',
        'Access control enforcement',
        'Security incident logging',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Sensor data validation',
        'Grid topology verification',
        'Data stream consistency',
        'Measurement reconciliation',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Anomaly pattern detection',
        'False positive filtering',
        'Threshold calibration',
        'Event classification',
      ],
      connections: ['prediction-agent', 'response-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Failure prediction modeling',
        'Load forecasting',
        'Weather impact analysis',
        'Cascade risk assessment',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Automated grid reconfiguration',
        'Crew dispatch optimization',
        'Outage notification',
        'Recovery coordination',
      ],
      connections: [],
    },
  ],

  'renewable-optimization': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Renewable asset authentication',
        'Grid connection security',
        'Data encryption management',
        'Access control monitoring',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Generation data validation',
        'Weather data verification',
        'Storage state confirmation',
        'Grid sync validation',
      ],
      connections: ['accuracy-agent', 'optimization-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Production forecast accuracy',
        'Curtailment detection',
        'Efficiency calculation',
        'Performance benchmarking',
      ],
      connections: ['optimization-agent', 'prediction-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Dispatch optimization',
        'Storage scheduling',
        'Curtailment minimization',
        'Revenue maximization',
      ],
      connections: ['prediction-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Weather pattern forecasting',
        'Generation prediction',
        'Demand forecasting',
        'Price prediction',
      ],
      connections: [],
    },
  ],

  'drilling-risk': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Drilling data protection',
        'Operational access control',
        'Geological data security',
        'Compliance documentation',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Sensor data validation',
        'Drilling parameter verification',
        'Mud log consistency',
        'Pressure data reconciliation',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Anomaly detection',
        'Kick detection accuracy',
        'Stuck pipe prediction',
        'Formation pressure analysis',
      ],
      connections: ['monitoring-agent', 'response-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Real-time parameter tracking',
        'Trend analysis',
        'Early warning detection',
        'Equipment health monitoring',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Automated parameter adjustment',
        'Emergency response coordination',
        'Crew alerting',
        'Mitigation execution',
      ],
      connections: [],
    },
  ],

  'environmental-compliance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Compliance data protection',
        'Regulatory access control',
        'Audit trail security',
        'Document encryption',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Emissions data validation',
        'Sensor calibration verification',
        'Regulatory data consistency',
        'Cross-system reconciliation',
      ],
      connections: ['accuracy-agent', 'compliance-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Leak detection accuracy',
        'Emissions calculation',
        'Threshold monitoring',
        'Violation prediction',
      ],
      connections: ['compliance-agent', 'monitoring-agent'],
    },
    {
      id: 'compliance-agent',
      name: 'Compliance Vanguard',
      type: 'compliance',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Regulatory mapping',
        'Permit tracking',
        'Violation prevention',
        'Report generation',
      ],
      connections: ['monitoring-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Continuous emissions monitoring',
        'Methane leak detection',
        'Flaring efficiency tracking',
        'Alert generation',
      ],
      connections: [],
    },
  ],

  'load-forecasting': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Forecast data protection',
        'Model access control',
        'API security management',
        'User authentication',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Historical data validation',
        'Weather data verification',
        'Smart meter data consistency',
        'Model input validation',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Forecast error analysis',
        'Model accuracy tracking',
        'Anomaly detection',
        'Performance benchmarking',
      ],
      connections: ['prediction-agent', 'optimization-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Load pattern prediction',
        'Peak demand forecasting',
        'Weather impact modeling',
        'EV charging prediction',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Generation scheduling',
        'Reserve optimization',
        'Market bidding strategy',
        'Demand response planning',
      ],
      connections: [],
    },
  ],

  'phmsa-compliance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Pipeline data security',
        'Inspection record protection',
        'Access control management',
        'Audit trail maintenance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Inspection data validation',
        'Pipeline integrity verification',
        'Maintenance record consistency',
        'Regulatory data accuracy',
      ],
      connections: ['accuracy-agent', 'compliance-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Defect detection accuracy',
        'Risk assessment precision',
        'Compliance score calculation',
        'Violation prediction',
      ],
      connections: ['compliance-agent', 'monitoring-agent'],
    },
    {
      id: 'compliance-agent',
      name: 'Compliance Vanguard',
      type: 'compliance',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'PHMSA regulation tracking',
        'Compliance gap analysis',
        'Report generation',
        'Corrective action planning',
      ],
      connections: ['monitoring-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Pipeline condition monitoring',
        'Inspection schedule tracking',
        'Compliance deadline alerts',
        'Performance monitoring',
      ],
      connections: [],
    },
  ],

  'methane-detection': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Sensor network security',
        'Detection data protection',
        'Access control enforcement',
        'Compliance documentation',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Sensor data validation',
        'Satellite imagery verification',
        'Ground sensor calibration',
        'Data fusion accuracy',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Leak detection precision',
        'Concentration measurement',
        'Source identification',
        'False positive reduction',
      ],
      connections: ['monitoring-agent', 'response-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Continuous methane monitoring',
        'Leak rate tracking',
        'Plume visualization',
        'Trend analysis',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Leak location dispatch',
        'Repair crew coordination',
        'Regulatory notification',
        'Mitigation tracking',
      ],
      connections: [],
    },
  ],

  'grid-resilience': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Critical infrastructure protection',
        'Cyber threat monitoring',
        'Access control management',
        'Security protocol enforcement',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Grid state validation',
        'Sensor data verification',
        'Topology consistency',
        'Communication integrity',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Threat detection accuracy',
        'Vulnerability assessment',
        'Impact prediction',
        'Recovery time estimation',
      ],
      connections: ['prediction-agent', 'response-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Weather impact forecasting',
        'Failure cascade modeling',
        'Load redistribution planning',
        'Recovery optimization',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Automated grid healing',
        'Resource mobilization',
        'Community coordination',
        'Service restoration',
      ],
      connections: [],
    },
  ],

  'internal-audit': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Audit data protection',
        'Access control enforcement',
        'Evidence chain custody',
        'Confidentiality management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Control testing validation',
        'Evidence verification',
        'Process consistency checks',
        'Data completeness validation',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Risk assessment accuracy',
        'Control effectiveness scoring',
        'Finding classification',
        'Materiality calculation',
      ],
      connections: ['analysis-agent', 'compliance-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Control gap analysis',
        'Risk pattern identification',
        'Root cause analysis',
        'Trend analysis',
      ],
      connections: ['compliance-agent'],
    },
    {
      id: 'compliance-agent',
      name: 'Compliance Vanguard',
      type: 'compliance',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Regulatory compliance tracking',
        'Remediation planning',
        'Report generation',
        'Management reporting',
      ],
      connections: [],
    },
  ],

  'scada-integration': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'SCADA security hardening',
        'Protocol authentication',
        'Intrusion detection',
        'Access control management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Protocol translation validation',
        'Data consistency verification',
        'System synchronization',
        'Message integrity checks',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Data mapping accuracy',
        'Translation precision',
        'Timestamp synchronization',
        'Value range validation',
      ],
      connections: ['monitoring-agent', 'optimization-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'System health monitoring',
        'Performance tracking',
        'Anomaly detection',
        'Integration status tracking',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Data flow optimization',
        'Latency reduction',
        'Resource allocation',
        'Throughput maximization',
      ],
      connections: [],
    },
  ],

  'predictive-resilience': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Multi-utility data security',
        'Cross-boundary authentication',
        'Federated access control',
        'Threat intelligence sharing',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Cross-utility data validation',
        'Topology verification',
        'State synchronization',
        'Boundary consistency',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Prediction accuracy tracking',
        'Model performance validation',
        'Scenario accuracy assessment',
        'Impact calculation precision',
      ],
      connections: ['prediction-agent', 'optimization-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Multi-region impact modeling',
        'Cascade failure prediction',
        'Resource need forecasting',
        'Recovery time estimation',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Resource allocation optimization',
        'Recovery sequence planning',
        'Cross-utility coordination',
        'Cost minimization',
      ],
      connections: [],
    },
  ],

  'cyber-defense': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Supply chain authentication',
        'Zero-trust enforcement',
        'Threat hunting',
        'Security orchestration',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Vendor risk validation',
        'Software integrity verification',
        'Configuration consistency',
        'Update authenticity checks',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Threat detection accuracy',
        'False positive reduction',
        'Attack pattern recognition',
        'Risk scoring precision',
      ],
      connections: ['monitoring-agent', 'response-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Continuous threat monitoring',
        'Behavioral analysis',
        'Anomaly detection',
        'Vendor activity tracking',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Automated containment',
        'Incident response coordination',
        'Threat neutralization',
        'Recovery execution',
      ],
      connections: [],
    },
  ],

  'wildfire-prevention': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Infrastructure data security',
        'Sensor network protection',
        'Access control management',
        'Compliance documentation',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Vegetation data validation',
        'Weather data verification',
        'Sensor calibration checks',
        'Satellite imagery validation',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Fire risk calculation accuracy',
        'Vegetation encroachment detection',
        'Weather impact assessment',
        'Equipment fault detection',
      ],
      connections: ['prediction-agent', 'response-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Fire spread modeling',
        'Risk zone prediction',
        'Weather pattern forecasting',
        'Equipment failure prediction',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Power shutoff coordination',
        'Vegetation crew dispatch',
        'Community notification',
        'Emergency response planning',
      ],
      connections: [],
    },
  ],
};