import { Agent } from '../vanguardAgents';

export const financialServicesAgents: { [key: string]: Agent[] } = {
  'fraud-detection': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Transaction encryption',
        'Authentication verification',
        'Security protocol enforcement',
        'Access pattern monitoring',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Transaction data validation',
        'Account consistency checks',
        'Cross-channel verification',
        'Data completeness validation',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Fraud pattern detection',
        'False positive reduction',
        'Risk score calculation',
        'Anomaly classification',
      ],
      connections: ['analysis-agent', 'response-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Behavioral analysis',
        'Network analysis',
        'Pattern recognition',
        'Threat intelligence integration',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Real-time blocking',
        'Alert generation',
        'Case creation',
        'Customer notification',
      ],
      connections: [],
    },
  ],

  'ai-credit-scoring': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Applicant data protection',
        'Model access control',
        'Decision encryption',
        'Compliance monitoring',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Credit data validation',
        'Income verification',
        'Identity confirmation',
        'Data source authentication',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Score accuracy validation',
        'Bias detection',
        'Model performance tracking',
        'Default prediction accuracy',
      ],
      connections: ['analysis-agent', 'compliance-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Alternative data analysis',
        'Risk factor assessment',
        'Creditworthiness evaluation',
        'Trend analysis',
      ],
      connections: ['compliance-agent'],
    },
    {
      id: 'compliance-agent',
      name: 'Compliance Vanguard',
      type: 'compliance',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Fair lending compliance',
        'Explainability generation',
        'Regulatory reporting',
        'Adverse action notices',
      ],
      connections: [],
    },
  ],

  'portfolio-optimization': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Portfolio data encryption',
        'Trading authorization',
        'API security management',
        'Access control enforcement',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Market data validation',
        'Position reconciliation',
        'Trade confirmation',
        'Price feed verification',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Performance attribution',
        'Risk calculation accuracy',
        'Benchmark tracking',
        'Return verification',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Market condition analysis',
        'Correlation analysis',
        'Factor exposure assessment',
        'Scenario analysis',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Asset allocation optimization',
        'Risk-return optimization',
        'Rebalancing strategy',
        'Tax optimization',
      ],
      connections: [],
    },
  ],

  'aml-monitoring': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Transaction data security',
        'Investigation access control',
        'Evidence protection',
        'Regulatory compliance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Transaction validation',
        'Customer data verification',
        'Cross-border consistency',
        'Sanctions list checking',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Pattern detection accuracy',
        'Risk scoring precision',
        'Alert quality assessment',
        'False positive reduction',
      ],
      connections: ['analysis-agent', 'compliance-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Transaction pattern analysis',
        'Network relationship mapping',
        'Behavioral profiling',
        'Typology identification',
      ],
      connections: ['compliance-agent'],
    },
    {
      id: 'compliance-agent',
      name: 'Compliance Vanguard',
      type: 'compliance',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'SAR filing automation',
        'Regulatory reporting',
        'Case documentation',
        'Audit trail maintenance',
      ],
      connections: [],
    },
  ],

  'insurance-risk': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Policyholder data protection',
        'Claims data security',
        'Access control management',
        'Privacy compliance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Application data validation',
        'Claims verification',
        'Medical record consistency',
        'Third-party data validation',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Risk assessment accuracy',
        'Premium calculation precision',
        'Claims prediction accuracy',
        'Fraud detection rates',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Risk factor analysis',
        'Claims pattern identification',
        'Catastrophe modeling',
        'Portfolio risk assessment',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Premium optimization',
        'Reserve optimization',
        'Reinsurance strategy',
        'Claims processing optimization',
      ],
      connections: [],
    },
  ],
};