import { Agent } from '../vanguardAgents';

export const healthcareAgents: { [key: string]: Agent[] } = {
  'patient-risk': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'HIPAA compliance enforcement',
        'Patient data encryption',
        'Access control management',
        'Audit trail generation',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Clinical data validation',
        'EHR consistency checks',
        'Lab result verification',
        'Medication reconciliation',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Risk score calculation',
        'Comorbidity detection',
        'Data quality assessment',
        'Predictive model accuracy',
      ],
      connections: ['analysis-agent', 'monitoring-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Clinical pattern analysis',
        'Risk factor identification',
        'Outcome prediction',
        'Intervention recommendations',
      ],
      connections: ['monitoring-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Real-time patient monitoring',
        'Alert generation',
        'Care team notification',
        'Escalation management',
      ],
      connections: [],
    },
  ],

  'clinical-trial-matching': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Patient privacy protection',
        'Trial data security',
        'Consent management',
        'De-identification processing',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Medical record validation',
        'Eligibility criteria verification',
        'Trial protocol consistency',
        'Data completeness checks',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Matching accuracy assessment',
        'Criteria interpretation',
        'False positive reduction',
        'Eligibility scoring',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Patient profile analysis',
        'Trial requirement matching',
        'Success probability calculation',
        'Site recommendation',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Enrollment optimization',
        'Site selection',
        'Patient distribution',
        'Timeline optimization',
      ],
      connections: [],
    },
  ],

  'treatment-recommendation': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Treatment data protection',
        'Provider authentication',
        'Decision audit trail',
        'Compliance monitoring',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Clinical guideline validation',
        'Drug interaction checking',
        'Contraindication verification',
        'Evidence base confirmation',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Treatment outcome prediction',
        'Side effect assessment',
        'Efficacy calculation',
        'Personalization accuracy',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Patient history analysis',
        'Genomic data interpretation',
        'Treatment response modeling',
        'Comparative effectiveness',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Treatment plan optimization',
        'Cost-effectiveness analysis',
        'Dosage optimization',
        'Schedule optimization',
      ],
      connections: [],
    },
  ],

  'diagnosis-assistant': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Diagnostic data security',
        'Provider verification',
        'Access logging',
        'Privacy compliance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Symptom data validation',
        'Test result verification',
        'Medical history consistency',
        'Image data integrity',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Diagnostic accuracy tracking',
        'Differential diagnosis ranking',
        'Confidence scoring',
        'Error pattern detection',
      ],
      connections: ['analysis-agent', 'prediction-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Symptom pattern analysis',
        'Medical literature review',
        'Similar case identification',
        'Diagnostic pathway mapping',
      ],
      connections: ['prediction-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Disease progression prediction',
        'Complication risk assessment',
        'Treatment response forecast',
        'Outcome prediction',
      ],
      connections: [],
    },
  ],

  'medical-supply-chain': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Supply chain data protection',
        'Vendor authentication',
        'Transaction security',
        'Access control management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Inventory data validation',
        'Order verification',
        'Supplier data consistency',
        'Quality certification checks',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Demand forecast accuracy',
        'Stock level verification',
        'Expiration tracking',
        'Usage pattern analysis',
      ],
      connections: ['monitoring-agent', 'optimization-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Real-time inventory tracking',
        'Supply disruption detection',
        'Critical stock alerts',
        'Temperature monitoring',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Order optimization',
        'Route optimization',
        'Stock level optimization',
        'Cost minimization',
      ],
      connections: [],
    },
  ],
};