import { Agent } from '../vanguardAgents';

export const manufacturingLogisticsAgents: { [key: string]: Agent[] } = {
  'predictive-maintenance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Equipment data protection',
        'Sensor network security',
        'Access control enforcement',
        'Maintenance record security',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Sensor data validation',
        'Equipment state verification',
        'Maintenance history consistency',
        'Calibration data accuracy',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Failure prediction accuracy',
        'Anomaly detection precision',
        'Performance degradation tracking',
        'False alarm reduction',
      ],
      connections: ['prediction-agent', 'optimization-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Failure mode prediction',
        'Remaining life estimation',
        'Maintenance window forecasting',
        'Parts failure prediction',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Maintenance scheduling',
        'Resource allocation',
        'Spare parts optimization',
        'Downtime minimization',
      ],
      connections: [],
    },
  ],

  'quality-inspection': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Inspection data security',
        'Quality record protection',
        'Access control management',
        'Compliance documentation',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Image data validation',
        'Measurement verification',
        'Batch consistency checks',
        'Calibration validation',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Defect detection accuracy',
        'Classification precision',
        'Measurement accuracy',
        'False positive reduction',
      ],
      connections: ['analysis-agent', 'response-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Defect pattern analysis',
        'Root cause identification',
        'Quality trend analysis',
        'Process correlation',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Line stoppage decisions',
        'Rework routing',
        'Quality alerts',
        'Process adjustment',
      ],
      connections: [],
    },
  ],

  'supply-chain': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Supply chain data security',
        'Vendor access control',
        'Transaction protection',
        'Blockchain integrity',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Order data validation',
        'Inventory reconciliation',
        'Shipment verification',
        'Supplier data consistency',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Demand forecast accuracy',
        'Lead time precision',
        'Inventory accuracy',
        'Delivery prediction',
      ],
      connections: ['prediction-agent', 'optimization-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Demand forecasting',
        'Supply disruption prediction',
        'Price trend forecasting',
        'Capacity planning',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Inventory optimization',
        'Route optimization',
        'Supplier selection',
        'Cost minimization',
      ],
      connections: [],
    },
  ],

  'demand-forecasting': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Sales data protection',
        'Forecast model security',
        'API access control',
        'Customer data privacy',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Historical data validation',
        'External data verification',
        'Promotion data consistency',
        'Market data accuracy',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Forecast accuracy tracking',
        'Model performance metrics',
        'Bias detection',
        'Error pattern analysis',
      ],
      connections: ['analysis-agent', 'prediction-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Seasonality analysis',
        'Trend identification',
        'Promotion impact analysis',
        'Market correlation',
      ],
      connections: ['prediction-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Demand prediction',
        'New product forecasting',
        'Regional demand modeling',
        'Long-term planning',
      ],
      connections: [],
    },
  ],

  'customer-personalization': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Customer data protection',
        'Privacy compliance',
        'Consent management',
        'Access control enforcement',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Profile data validation',
        'Behavior data consistency',
        'Cross-channel reconciliation',
        'Preference verification',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Recommendation accuracy',
        'Preference prediction precision',
        'Segmentation accuracy',
        'Engagement tracking',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Behavior pattern analysis',
        'Journey mapping',
        'Preference extraction',
        'Cohort analysis',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Content optimization',
        'Offer personalization',
        'Channel optimization',
        'Timing optimization',
      ],
      connections: [],
    },
  ],

  'price-optimization': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Pricing data security',
        'Competitor data protection',
        'Algorithm access control',
        'Audit trail maintenance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Cost data validation',
        'Market price verification',
        'Inventory data consistency',
        'Competitor price accuracy',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Elasticity calculation accuracy',
        'Revenue impact precision',
        'Margin calculation',
        'Competitive position tracking',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Price elasticity analysis',
        'Competitive analysis',
        'Customer segment analysis',
        'Seasonality impact',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Dynamic price optimization',
        'Markdown optimization',
        'Bundle pricing',
        'Revenue maximization',
      ],
      connections: [],
    },
  ],

  'route-optimization': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Route data protection',
        'Driver data security',
        'GPS tracking privacy',
        'Access control management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Address validation',
        'Traffic data verification',
        'Vehicle capacity checks',
        'Time window consistency',
      ],
      connections: ['accuracy-agent', 'optimization-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'ETA accuracy',
        'Distance calculation precision',
        'Traffic prediction accuracy',
        'Delivery success tracking',
      ],
      connections: ['optimization-agent', 'monitoring-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Route optimization',
        'Load balancing',
        'Time window optimization',
        'Fuel efficiency',
      ],
      connections: ['monitoring-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Real-time tracking',
        'Delay detection',
        'Driver performance',
        'Customer notifications',
      ],
      connections: [],
    },
  ],

  'fleet-maintenance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Vehicle data security',
        'Maintenance record protection',
        'Telematics data privacy',
        'Access control enforcement',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Sensor data validation',
        'Maintenance history verification',
        'Parts inventory consistency',
        'Compliance data accuracy',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Failure prediction accuracy',
        'Wear pattern detection',
        'Cost estimation precision',
        'Downtime prediction',
      ],
      connections: ['prediction-agent', 'optimization-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Component failure prediction',
        'Maintenance need forecasting',
        'Parts demand prediction',
        'Vehicle lifecycle modeling',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Maintenance scheduling',
        'Parts inventory optimization',
        'Workshop utilization',
        'Cost optimization',
      ],
      connections: [],
    },
  ],

  'warehouse-automation': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Warehouse data security',
        'Robot access control',
        'Inventory data protection',
        'System integrity monitoring',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Inventory count validation',
        'Location data verification',
        'Order data consistency',
        'System synchronization',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Pick accuracy tracking',
        'Inventory accuracy',
        'Location precision',
        'Throughput measurement',
      ],
      connections: ['monitoring-agent', 'optimization-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Robot health monitoring',
        'System performance tracking',
        'Bottleneck detection',
        'Safety monitoring',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Pick path optimization',
        'Storage optimization',
        'Robot coordination',
        'Throughput maximization',
      ],
      connections: [],
    },
  ],
};