import { Agent } from '../vanguardAgents';

export const otherVerticalsAgents: { [key: string]: Agent[] } = {
  // Education & EdTech
  'adaptive-learning': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Student data protection',
        'FERPA compliance',
        'Access control management',
        'Content security',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Learning data validation',
        'Assessment integrity',
        'Progress tracking consistency',
        'Content accuracy verification',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Learning outcome measurement',
        'Skill assessment accuracy',
        'Progress tracking precision',
        'Recommendation accuracy',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Learning pattern analysis',
        'Knowledge gap identification',
        'Performance trend analysis',
        'Engagement metrics',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Learning path optimization',
        'Content sequencing',
        'Difficulty adjustment',
        'Time optimization',
      ],
      connections: [],
    },
  ],

  'student-performance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Student record security',
        'Privacy protection',
        'Access control enforcement',
        'Data anonymization',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Academic data validation',
        'Attendance verification',
        'Grade consistency checks',
        'Behavioral data accuracy',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Risk assessment accuracy',
        'Performance prediction precision',
        'Intervention effectiveness',
        'Success metric tracking',
      ],
      connections: ['prediction-agent', 'monitoring-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Dropout risk prediction',
        'Performance forecasting',
        'Success probability modeling',
        'Intervention timing',
      ],
      connections: ['monitoring-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Real-time performance tracking',
        'Early warning alerts',
        'Intervention monitoring',
        'Progress reporting',
      ],
      connections: [],
    },
  ],

  'content-recommendation': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Content access control',
        'User data protection',
        'Copyright compliance',
        'API security',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Content quality validation',
        'Metadata verification',
        'User preference consistency',
        'Learning objective alignment',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Recommendation relevance',
        'Match accuracy scoring',
        'Engagement prediction',
        'Learning outcome tracking',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Content effectiveness analysis',
        'User behavior patterns',
        'Learning style identification',
        'Engagement analysis',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Content mix optimization',
        'Delivery timing',
        'Format selection',
        'Personalization tuning',
      ],
      connections: [],
    },
  ],

  // Pharmaceutical & Biotech
  'drug-discovery': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Research data protection',
        'IP security management',
        'Access control enforcement',
        'Collaboration security',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Molecular data validation',
        'Experiment data verification',
        'Literature consistency',
        'Protocol compliance',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Prediction accuracy tracking',
        'Binding affinity precision',
        'Toxicity prediction accuracy',
        'Success probability scoring',
      ],
      connections: ['analysis-agent', 'prediction-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Structure-activity analysis',
        'Target identification',
        'Pathway analysis',
        'Side effect prediction',
      ],
      connections: ['prediction-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Efficacy prediction',
        'Clinical trial outcome',
        'Drug interaction modeling',
        'Market success forecasting',
      ],
      connections: [],
    },
  ],

  'clinical-trial-optimization': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Trial data security',
        'Patient privacy protection',
        'Regulatory compliance',
        'Site access control',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Protocol adherence verification',
        'Data quality validation',
        'Site performance consistency',
        'Patient data accuracy',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Enrollment prediction accuracy',
        'Site selection precision',
        'Timeline estimation',
        'Cost prediction accuracy',
      ],
      connections: ['monitoring-agent', 'optimization-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Trial progress monitoring',
        'Adverse event tracking',
        'Protocol deviation alerts',
        'Enrollment tracking',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Site allocation optimization',
        'Recruitment strategy',
        'Resource optimization',
        'Timeline optimization',
      ],
      connections: [],
    },
  ],

  'adverse-event': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Patient data security',
        'Report confidentiality',
        'Access control management',
        'Regulatory compliance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Event data validation',
        'Source verification',
        'Report consistency',
        'Timeline accuracy',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Signal detection accuracy',
        'Causality assessment',
        'Severity classification',
        'Pattern recognition precision',
      ],
      connections: ['monitoring-agent', 'response-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Real-time event monitoring',
        'Signal detection',
        'Trend analysis',
        'Regulatory reporting',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Alert generation',
        'Regulatory notification',
        'Risk mitigation',
        'Label updates',
      ],
      connections: [],
    },
  ],

  // Government & Public Sector
  'emergency-response': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Emergency data security',
        'Communication encryption',
        'Access control management',
        'Inter-agency authentication',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Incident data validation',
        'Resource availability verification',
        'Location data accuracy',
        'Communication integrity',
      ],
      connections: ['accuracy-agent', 'response-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Threat assessment accuracy',
        'Resource need prediction',
        'Impact estimation',
        'Response time calculation',
      ],
      connections: ['response-agent', 'optimization-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Resource dispatch',
        'Multi-agency coordination',
        'Public alerting',
        'Evacuation management',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Resource allocation',
        'Route optimization',
        'Coverage maximization',
        'Response prioritization',
      ],
      connections: [],
    },
  ],

  'infrastructure-coordination': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Infrastructure data protection',
        'Cross-sector security',
        'Threat intelligence sharing',
        'Access control federation',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Dependency mapping validation',
        'System state verification',
        'Cross-sector data consistency',
        'Communication integrity',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Threat detection accuracy',
        'Impact assessment precision',
        'Cascade prediction accuracy',
        'Recovery time estimation',
      ],
      connections: ['monitoring-agent', 'response-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Cross-sector monitoring',
        'Threat detection',
        'Dependency tracking',
        'Performance monitoring',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Coordinated response',
        'Sector isolation',
        'Recovery orchestration',
        'Communication management',
      ],
      connections: [],
    },
  ],

  'citizen-services': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Citizen data protection',
        'Identity verification',
        'Service access control',
        'Privacy compliance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Application data validation',
        'Document verification',
        'Eligibility confirmation',
        'Cross-agency consistency',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Service matching accuracy',
        'Eligibility assessment',
        'Processing time estimation',
        'Benefit calculation precision',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Service need analysis',
        'Usage pattern identification',
        'Eligibility analysis',
        'Impact assessment',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Service delivery optimization',
        'Resource allocation',
        'Queue management',
        'Channel optimization',
      ],
      connections: [],
    },
  ],

  'public-safety': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Crime data security',
        'Officer safety protocols',
        'Evidence protection',
        'Access control management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Incident data validation',
        'Evidence chain custody',
        'Report accuracy verification',
        'Cross-system consistency',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Crime prediction accuracy',
        'Pattern recognition precision',
        'Risk assessment accuracy',
        'Resource need estimation',
      ],
      connections: ['prediction-agent', 'response-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Crime hotspot prediction',
        'Incident forecasting',
        'Resource need prediction',
        'Pattern evolution modeling',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Patrol optimization',
        'Resource deployment',
        'Community engagement',
        'Emergency response',
      ],
      connections: [],
    },
  ],

  'resource-optimization': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Budget data security',
        'Procurement protection',
        'Access control enforcement',
        'Audit trail security',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Spending data validation',
        'Contract verification',
        'Budget consistency checks',
        'Performance data accuracy',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Cost estimation accuracy',
        'Savings calculation precision',
        'Efficiency measurement',
        'ROI calculation accuracy',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Spending pattern analysis',
        'Waste identification',
        'Efficiency analysis',
        'Benchmark comparison',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Budget optimization',
        'Resource allocation',
        'Procurement optimization',
        'Service consolidation',
      ],
      connections: [],
    },
  ],

  // Telecommunications
  'network-performance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Network data security',
        'Traffic encryption',
        'Access control management',
        'DDoS protection',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Traffic data validation',
        'Configuration verification',
        'Topology consistency',
        'Performance data accuracy',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Performance metric accuracy',
        'Fault detection precision',
        'Capacity prediction accuracy',
        'QoS measurement',
      ],
      connections: ['monitoring-agent', 'optimization-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Real-time performance monitoring',
        'Anomaly detection',
        'Capacity tracking',
        'Service quality monitoring',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Traffic optimization',
        'Capacity planning',
        'Route optimization',
        'Resource allocation',
      ],
      connections: [],
    },
  ],

  'churn-prevention': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Customer data protection',
        'Behavioral data security',
        'Privacy compliance',
        'Access control management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Customer data validation',
        'Usage data verification',
        'Billing data consistency',
        'Interaction history accuracy',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Churn prediction accuracy',
        'Risk scoring precision',
        'Lifetime value calculation',
        'Retention probability',
      ],
      connections: ['prediction-agent', 'optimization-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Churn risk prediction',
        'Behavior change detection',
        'Value trend forecasting',
        'Competitive threat assessment',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Retention offer optimization',
        'Engagement strategy',
        'Channel optimization',
        'Timing optimization',
      ],
      connections: [],
    },
  ],

  'network-security': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Threat intelligence management',
        'Security policy enforcement',
        'Incident response coordination',
        'Vulnerability management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Traffic pattern validation',
        'Configuration integrity',
        'Log data verification',
        'Alert consistency checks',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Threat detection accuracy',
        'False positive reduction',
        'Attack classification precision',
        'Risk scoring accuracy',
      ],
      connections: ['monitoring-agent', 'response-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Real-time threat monitoring',
        'Behavioral analysis',
        'Anomaly detection',
        'Compliance monitoring',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Automated threat response',
        'Incident containment',
        'Recovery orchestration',
        'Forensic analysis',
      ],
      connections: [],
    },
  ],

  // Real Estate
  'ai-pricing-governance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Pricing model security',
        'Property data protection',
        'Algorithm access control',
        'Audit trail maintenance',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Market data validation',
        'Property data verification',
        'Comparable consistency',
        'Algorithm integrity checks',
      ],
      connections: ['accuracy-agent', 'compliance-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Pricing accuracy measurement',
        'Valuation precision tracking',
        'Market prediction accuracy',
        'Bias detection metrics',
      ],
      connections: ['compliance-agent', 'optimization-agent'],
    },
    {
      id: 'compliance-agent',
      name: 'Compliance Vanguard',
      type: 'compliance',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Fair housing compliance',
        'Regulatory adherence',
        'Bias prevention',
        'Transparency requirements',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Pricing strategy optimization',
        'Market timing',
        'Portfolio optimization',
        'Revenue maximization',
      ],
      connections: [],
    },
  ],

  'property-valuation': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Valuation data security',
        'Client information protection',
        'Model security',
        'Access control',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Property data validation',
        'Comparable verification',
        'Market data consistency',
        'Inspection data accuracy',
      ],
      connections: ['accuracy-agent', 'analysis-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Valuation accuracy tracking',
        'Model precision metrics',
        'Market adjustment accuracy',
        'Confidence scoring',
      ],
      connections: ['analysis-agent', 'optimization-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Market trend analysis',
        'Comparable analysis',
        'Risk factor assessment',
        'Value driver identification',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Valuation model optimization',
        'Data source optimization',
        'Process efficiency',
        'Accuracy improvement',
      ],
      connections: [],
    },
  ],

  'market-analysis': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Market data security',
        'Proprietary analysis protection',
        'Client data security',
        'API security',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Market data validation',
        'Source verification',
        'Data consistency checks',
        'Time series integrity',
      ],
      connections: ['accuracy-agent', 'prediction-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Forecast accuracy tracking',
        'Trend prediction precision',
        'Market timing accuracy',
        'Confidence intervals',
      ],
      connections: ['prediction-agent', 'analysis-agent'],
    },
    {
      id: 'prediction-agent',
      name: 'Prediction Vanguard',
      type: 'prediction',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Market trend forecasting',
        'Price movement prediction',
        'Demand forecasting',
        'Supply analysis',
      ],
      connections: ['analysis-agent'],
    },
    {
      id: 'analysis-agent',
      name: 'Analysis Vanguard',
      type: 'analysis',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Market segmentation',
        'Competitive analysis',
        'Opportunity identification',
        'Risk assessment',
      ],
      connections: [],
    },
  ],

  // Cross-Industry / All Verticals
  'ai-governance': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'AI system security',
        'Model protection',
        'Data privacy enforcement',
        'Access control management',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Model integrity verification',
        'Data quality validation',
        'Bias detection',
        'Ethical compliance',
      ],
      connections: ['accuracy-agent', 'compliance-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Model performance tracking',
        'Prediction accuracy metrics',
        'Drift detection',
        'Confidence scoring',
      ],
      connections: ['compliance-agent', 'monitoring-agent'],
    },
    {
      id: 'compliance-agent',
      name: 'Compliance Vanguard',
      type: 'compliance',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Regulatory compliance',
        'Ethical guidelines adherence',
        'Transparency requirements',
        'Audit trail maintenance',
      ],
      connections: ['monitoring-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Continuous monitoring',
        'Performance tracking',
        'Anomaly detection',
        'Alert management',
      ],
      connections: [],
    },
  ],

  'data-quality': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Data access security',
        'Pipeline security',
        'Encryption management',
        'Access logging',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Data validation rules',
        'Consistency checking',
        'Duplicate detection',
        'Schema enforcement',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Quality metrics tracking',
        'Completeness measurement',
        'Accuracy scoring',
        'Timeliness monitoring',
      ],
      connections: ['monitoring-agent', 'optimization-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Real-time quality monitoring',
        'Anomaly detection',
        'Trend analysis',
        'Alert generation',
      ],
      connections: ['optimization-agent'],
    },
    {
      id: 'optimization-agent',
      name: 'Optimization Vanguard',
      type: 'optimization',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Quality improvement',
        'Process optimization',
        'Resource allocation',
        'Performance tuning',
      ],
      connections: [],
    },
  ],

  'model-monitoring': [
    {
      id: 'security-agent',
      name: 'Security Vanguard',
      type: 'security',
      status: 'inactive',
      position: { x: 100, y: 100 },
      tasks: [
        'Model access security',
        'Prediction data protection',
        'API security',
        'Audit logging',
      ],
      connections: ['integrity-agent', 'accuracy-agent'],
    },
    {
      id: 'integrity-agent',
      name: 'Integrity Vanguard',
      type: 'integrity',
      status: 'inactive',
      position: { x: 300, y: 100 },
      tasks: [
        'Model version control',
        'Input data validation',
        'Output consistency',
        'Feature integrity',
      ],
      connections: ['accuracy-agent', 'monitoring-agent'],
    },
    {
      id: 'accuracy-agent',
      name: 'Accuracy Vanguard',
      type: 'accuracy',
      status: 'inactive',
      position: { x: 500, y: 100 },
      tasks: [
        'Performance metrics tracking',
        'Drift detection',
        'Accuracy monitoring',
        'Bias measurement',
      ],
      connections: ['monitoring-agent', 'response-agent'],
    },
    {
      id: 'monitoring-agent',
      name: 'Monitoring Vanguard',
      type: 'monitoring',
      status: 'inactive',
      position: { x: 200, y: 300 },
      tasks: [
        'Real-time monitoring',
        'Anomaly detection',
        'Performance tracking',
        'Resource monitoring',
      ],
      connections: ['response-agent'],
    },
    {
      id: 'response-agent',
      name: 'Response Vanguard',
      type: 'response',
      status: 'inactive',
      position: { x: 400, y: 300 },
      tasks: [
        'Alert response',
        'Model retraining triggers',
        'Rollback management',
        'Incident handling',
      ],
      connections: [],
    },
  ],
};