global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'seraphim-vanguard'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Backend API monitoring
  - job_name: 'seraphim-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['seraphim-backend:3001']
        labels:
          service: 'backend'
          component: 'api'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node.js application metrics
  - job_name: 'nodejs'
    static_configs:
      - targets: ['seraphim-backend:3001']
        labels:
          service: 'backend'
          runtime: 'nodejs'

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'
          component: 'cache'

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
        labels:
          service: 'nginx'
          component: 'proxy'

  # Docker containers monitoring
  - job_name: 'docker'
    static_configs:
      - targets: ['172.20.0.1:9323']
        labels:
          service: 'docker'

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://seraphim-vanguard.com
        - https://seraphim-vanguard.com/api/health
        - https://seraphim-vanguard.com/api/auth/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Service discovery for dynamic targets
# - job_name: 'kubernetes-pods'
#   kubernetes_sd_configs:
#     - role: pod
#   relabel_configs:
#     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#       action: keep
#       regex: true
#     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
#       action: replace
#       target_label: __metrics_path__
#       regex: (.+)